server:
  port: 8082

spring:
  application:
    name: device-gateway

kafka:
  consumer:
    bootstrap-servers: localhost:9092
    group-id: device-gateway
    auto-offset-reset: earliest
    topic: device-commands
    concurrency: 3
    ack-mode: MANUAL

app:
  clients:
    command-service:
      base-url: http://localhost:8081
    device-service:
      base-url: http://localhost:8080
  command-executor:
    core-pool-size: 10
    max-pool-size: 10
    queue-capacity: 200
    await-termination-seconds: 10
  netconf:
    username: netconf
    password: netconf

logging:
  level:
    org.springframework.kafka: DEBUG
    org.apache.kafka.clients.consumer: DEBUG
    org.apache.kafka.clients.NetworkClient: INFO
